### ISSUE TITLE
GetById中的问题

### ISSUE THREAD

**Issue by scudfly** [anet-team/anet#2]
很棒的框架，但我在使用中发现了一个问题
` public AnetUser GetByIdAsync(long id)
  {
        var sql = Sql.Select("AnetUser", new { Id = id });
        return Db.QueryFirstOrDefault<AnetUser>(sql);
  }`
在这个方法中sql最终的拼接结果为SELECT * FROM AnetUser WHERE Id=@Id，
传入的参数id并未使用，所以在下一步执行时会报@Id未声明的异常，
若将参数传入执行语句可正常运行，如Db.QueryFirstOrDefault<AnetUser>(sql, new { Id = id });
这里是否有问题

**Comment by liamwang** [comment]
@scudfly 感谢反馈，已经修复。
