### ISSUE TITLE
关于项目中Scheduler的疑问

### ISSUE THREAD

**Issue by xiaoxiaotank** [anet-team/anet#6]
&emsp;&emsp;在看了anet项目后，我对Scheduler的设计有点疑问，希望能够得到解惑！

&emsp;&emsp;对于以下代码，否表示在12秒后开始执行任务？并且每2秒钟执行一次？
&emsp;&emsp;`Scheduler.StartNewAt<MessageJob>(DateTime.Now.AddSeconds(10), TimeSpan.FromSeconds(2), false);`

&emsp;&emsp;如果是的话，我再MessageJob中记录了一下时间，发现和所预期的不一样，该任务在10秒后就被立即调度了，并且每隔4秒才执行一次。
&emsp;&emsp;后来经过阅读代码，发现在`GetNextTimeToRun`方法中如果当前时间小于开始时间，则该任务的调度时间就为开始时间，不应该如此吧？而且，在`UpdateTimer`中，通过`Change`方法重新设置了启动时间和间隔时长，导致2秒变成了4秒。

&emsp;&emsp;可能是由于我没有了解该调度程序的作用，希望能解释一下是否为故意设计的！！

**Comment by Zaeworks** [comment]
当开始时间小于当前时间时, executeAtStartTime参数是有效的, 这个设计主要是为了方便发起定期任务:
> 比如我现在(19点)发起一个每天12点执行的任务, startTime设为`DateTime.Toady.AddHours(12)`, 如果executeAtStartTime为true, 那么现在会补发此任务,否则就要等到下一天的12点执行.

- 参数的实际作用就是**当startTime小于当前时间时, 是否立刻补发一次任务**; startTime大于当前时间时这个参数不起作用(也就是到了startTime直接执行).


2秒变4秒的原因是任务执行时长高于任务间隔:
- 调度器会在运行时监测是否有同类任务, 如果有则此次调度不执行; 在MessageJob的例子中, 这个任务执行时长为3秒, 调度间隔为2秒, 所以会有每两次调度就有一次不执行的情况
- 如果想要发起执行时长大于调度间隔的任务, 可以在任务里再包一个Task, 但调度器不会捕获异常:
```csharp
        public async Task ExecuteAsync()
        {
            Task.Run(() =>
            {
                // 模拟发送消息
                _logger.LogInformation("正在发送消息...");
                Thread.Sleep(3000);
                _logger.LogInformation("消息发送成功。");
            });
        }
```
> 这个机制主要是为了防止定时任务积压, 在使用时建议任务间隔高于任务时长

另外这两个设计都有点僵硬, 有空我会改进😵
