### ISSUE TITLE
对数据库读写分离的时候怎么处理？

### ISSUE THREAD

**Issue by chenbigit** [anet-team/anet#8]
对数据库读写分离的时候怎么处理？

**Comment by liamwang** [comment]
不好意思，前段时间比较忙，没回复这个Issue。

读写分离是架构层面的，理论上和ORM无关，Anet 使用的是 Dapper。但如果使用SQL拦截器的方式实现数据库读写分离，对 Dappner 扩展一个 SQL 执行的勾子可以更方便地实现数据库读写分离。

已将“添加SQL执行勾子”列入Roadmap。
